---
- hosts: 10.0.0.236 
  become: yes
  become_user: root
  remote_user: ubuntu
  vars:
    http_port: 80
    domain: paddy.com 
  tasks:
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest

    - name: install index page
      copy: src=front.html dest=/var/www/html/index.html backup=yes
      tags: configure
      notify: restart apache2

    - name: enabled mod_rewrite
      apache2_module: name=rewrite state=present
      notify: restart apache2

    - name: apache2 listen on port {{ http_port }}
      lineinfile: dest=/etc/apache2/apache2.conf regexp="^Listen " line="Listen {{ http_port }}" state=present
      notify: restart apache2

    - name: apache2 virtualhost on port {{ http_port }}
      lineinfile: dest=/etc/apache2/apache2.conf regexp="^<VirtualHost \*:" line="<VirtualHost *:{{ http_port }}>"
      notify: restart apache2

    - name: create virtual host file
      template: src=virtualhost.conf dest=/etc/apache2/apache2.conf

    - name: Transfer the script
      copy: src=/home/ubuntu/testweb.sh dest=/home/ubuntu mode=0755
# wait 300 seconds for port 8000 to become open on the host, don't start checking for 10 seconds
    - wait_for: port=80 delay=10

    - name: Execute the script

      command: sh /home/ubuntu/testweb.sh

